steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/your-username/your-repo.git', '.']
  - name: 'gcr.io/buildpacks/builder:v1'
    args: ['pack', 'build', '--builder=gcr.io/buildpacks/builder', 'gcr.io/YOUR_PROJECT_ID/your-image-name']

images: ['gcr.io/YOUR_PROJECT_ID/your-image-name']
